### ISSUE TITLE
crashes when clicking on a particular clue of a puzzle

### ISSUE THREAD

**Issue by cameronfreer** [downforacross/downforacross.com#113]
The Monday, April 20, 2020 NY Times (Lynn Lempel) puzzle crashes (immediately clears to a white screen) when clicking on 66 across (either via the clue or the grid).

generate new puzzle: https://downforacross.com/beta/play/5530
filled: https://downforacross.com/beta/game/448276-glemp

**Comment by stevenhao** [comment]
Confirmed the bug. Pushing a fix.

**Comment by stevenhao** [comment]
![image](https://user-images.githubusercontent.com/1988030/92518582-6a2ac900-f1cd-11ea-9763-b380d38ae72b.png)
referenced clues no longer crashes!
