### ISSUE TITLE
Getting dev backend to talk to frontend

### ISSUE THREAD

**Issue by TMiguelT** [downforacross/downforacross.com#116]
I'm trying to set up the dev environment.

For the backend I ran the instructions detailed here: https://github.com/downforacross/downforacross.com/tree/master/server#getting-started. For the frontend I ran these commands: https://github.com/downforacross/downforacross.com#getting-started.

However, while both appear to be working, uploading a `.puz` file appears to do nothing, and I can't see it on the puzzle list. Any pointers?

**Comment by stevenhao** [comment]
I need to update these docs, thanks for the reminder!

### Running frontend-only, talking to a shared backend (api-staging.foracross.com):
- `yarn start`

### Running local backend and local frontend that talk to each other:
- `yarn devbackend`
- `yarn devfrontend`

**Comment by stevenhao** [comment]
Not sure why uploading a puz does nothing when you run `yarn start`, it should append to the puzzlelist in firebase (though I am actually working on migrating the entire puzzlelist & puzzle repo to postgres -- stay tuned).

**Comment by TMiguelT** [comment]
Great, thanks for the clarification. Actually when I originally used `yarn start` I had an empty puzzle list, but now when I do it I'm able to see everything I uploaded.
