### ISSUE TITLE
Solve count broken?

### ISSUE THREAD

**Issue by TMiguelT** [downforacross/downforacross.com#121]
I've noticed for a few weeks that the solve counts all seem to be 0:

![image](https://user-images.githubusercontent.com/5019367/94758681-1fbdf600-03e1-11eb-8f09-328475111d39.png)

**Comment by stevenhao** [comment]
I plan to fix this as part of migrating puzzles & puzzle stats from firebase to postgres. Perhaps sometime in the next 2 weeks.

**Comment by TMiguelT** [comment]
That would be good. Any thoughts on what happened? (I'm just interested)

**Comment by stevenhao** [comment]
Acknowledging that my time estimates have not been the best in the past, I'm hoping to finish the migration of the puzzle repo sometime this week!

**Comment by frozenpandaman** [comment]
Seems to be fixed now!

**Comment by TMiguelT** [comment]
Indeed! Closing.
