### ISSUE TITLE
Circles are in the wrong spot for some puzzles

### ISSUE THREAD

**Issue by cameronfreer** [downforacross/downforacross.com#122]
On several, but not all, circle puzzles (see example below), the circles are in the wrong spot -- sometimes elsewhere within the same word, other times farther away from the correct location. As far as I can tell, they are generally in the same wrong spot for all copies of the same puzzle, and have the correct number of circles, just wrong locations. Maybe there's some issue with the .puz parser?

Example:
NY Times, Sun, Aug 05, 2018 GHOSTED
Daily Puzzle | By Alison Ohringer and Erik Agard / Will Shortz
https://downforacross.com/beta/play/9302
https://downforacross.com/beta/play/6313
https://downforacross.com/beta/play/2992
![image](https://user-images.githubusercontent.com/2009342/95688625-80b3ae00-0bd9-11eb-8e69-41a1588992f1.png)

Correct location (from [xwordinfo](https://www.xwordinfo.com/Crossword?date=8/5/2018))
![image](https://user-images.githubusercontent.com/2009342/95688656-a6d94e00-0bd9-11eb-9463-ad6e913a8fa3.png)

**Comment by stevenhao** [comment]
hmm, interesting. agree this is probably a bug with the puz parser.

**Comment by cameronfreer** [comment]
Here's another example:

NY Times, Tuesday, September 5, 2017
Daily Puzzle | By Michelle Kenney and Jeff Chen / Will Shortz
https://downforacross.com/beta/play/10144
![image](https://user-images.githubusercontent.com/2009342/101291295-b0e08d00-37d5-11eb-94fc-ededaa422c00.png)

Correct location (from [xwordinfo](https://www.xwordinfo.com/Crossword?date=9/5/2017))
![image](https://user-images.githubusercontent.com/2009342/101291312-d5d50000-37d5-11eb-8853-eabf5b209e03.png)
