### ISSUE TITLE
Bug: Cryptic crosswords crash on Android phones

### ISSUE THREAD

**Issue by dpsanders** [downforacross/downforacross.com#131]
On an Android phone, clicking on a square that is not the intersection of an across and down in a cryptic crossword results in just a blank page being displayed.

Tested on two recent Samsung smartphones.

**Comment by stevenhao** [comment]
Thanks for the report! Will look into this.

**Comment by dpsanders** [comment]
Thanks!

**Comment by stevenhao** [comment]
![image](https://user-images.githubusercontent.com/1988030/103160478-82c5eb80-478a-11eb-93c1-430fbc09bd35.png)
I was able to reproduce this using chrome dev tool's device simulator. Should be able to put up a patch shortly.

**Comment by dpsanders** [comment]
I can confirm that the fix works. Many thanks!

**Comment by dpsanders** [comment]
Just wanted to say that DFAC is a fantastic site, thanks!
