### ISSUE TITLE
Puzzles not being created

### ISSUE THREAD

**Issue by TMiguelT** [downforacross/downforacross.com#158]
If I open a new puzzle, the website gets stuck on "Creating game...", and if I come back to that game, the page is blank:
![image](https://user-images.githubusercontent.com/5019367/105689772-48996680-5f4f-11eb-93ff-01c54b330c3e.png)

The console logs doesn't reveal anything amiss:

```
Game.js:103 initialize game
Game.js:104 listening ws
game.js:169 subscribed
getSocket.ts:35 Connecting to https://api.foracross.com
user.js:21 Your id is 46327c8
getSocket.ts:23 [ws connect] undefined
getSocket.ts:26 [ws connect] undefined
getSocket.ts:29 [ws ping] 1611568361867
getSocket.ts:32 [ws pong] 1611568362056
getSocket.ts:29 [ws ping] 1611568364056
getSocket.ts:32 [ws pong] 1611568364244
getSocket.ts:29 [ws ping] 1611568366244
getSocket.ts:32 [ws pong] 1611568366436
getSocket.ts:29 [ws ping] 1611568368917
getSocket.ts:32 [ws pong] 1611568369103
getSocket.ts:29 [ws ping] 1611568371104
getSocket.ts:32 [ws pong] 1611568371294
getSocket.ts:29 [ws ping] 1611568373296
getSocket.ts:32 [ws pong] 1611568373484
```

**Comment by cpburke91** [comment]
I am encountering the same issue as of this morning.

**Comment by auntiviris** [comment]
Same here. Issue is affecting me and several friends.

**Comment by stevenhao** [comment]
That is strange. I restarted the server and that solved the issue. I suspect that some of the recent backend changes might've overloaded the api server, perhaps causing OOM issues and crashing the process entirely. 

I'll look into running the api server in a separate deployment (considering https://vercel.com/docs/serverless-functions/introduction) to prevent this from happening.

**Comment by stevenhao** [comment]
Seems like the issue occurs when `POST /api/record_solve` is hit. i'll look into this more later in the day, going to make a change to stub that route for now and close this issue.

**Comment by jvigilan** [comment]
Uh before you close this, have you tested trying to play a puzzle? Answers are disappearing...synced shows on the bottom 57 msecs - (1 sec)

**Comment by stevenhao** [comment]
Bug was introduced by me last night, forgot to close a db connection in a route handler 😨.
Discussion here: https://github.com/downforacross/downforacross.com/pull/153#discussion_r563954015
Fix here: https://github.com/downforacross/downforacross.com/commit/56b99f3a923dde428fca562b7cf3d72f794b916f
