### ISSUE TITLE
Shift-Arrow keyboard navigation

### ISSUE THREAD

**Issue by danoa** [downforacross/downforacross.com#164]
Make it possible to move cursor perpendicular to current orientation without changing orientation, using the same keyboard shortcuts as Across Lite. This functionality exists and is currently mapped to characters '[' and ']'. These characters are hard to press on many international keyboards, so having the additional mappings of Shift-Arrow keys would be beneficial.

**Comment by stevenhao** [comment]
I haven't used Across Lite but this sounds reasonable. I can't think of any reason not to do this, PRs welcome!

**Comment by danoa** [comment]
Thank you for the fix, this works great! <3
