### ISSUE TITLE
feature request: emoji for :codes: in chat

### ISSUE THREAD

**Issue by jakob223** [downforacross/downforacross.com#17]
👍 from `:thumbsup:` for example

Progress Update:
- [x] convert emojis in chatbar
- [ ] add some autocomplete suggestions when typing

**Comment by jakob223** [comment]
Twemoji comes with some :things: by default I think


--Jakob

**Comment by stevenhao** [comment]
i have some WIP that auto-converts `:emojiname:` to unicode emojis. To make this usable & discoverable by the lay-person:
- add some autocomplete suggestions when typing
- e.g. slack's ui starts autocompleting after typing `:` followed by any 2 letters (see screenshot).
![image](https://user-images.githubusercontent.com/1988030/44358030-9fd6ab00-a468-11e8-96c6-166c82d56e89.png)

Relevant commits: 
https://github.com/downforacross/downforacross.com/commit/708bf7c6b7036f6037ab1a400a01a6e44423f8e0 (adds emojis)
https://github.com/downforacross/downforacross.com/commit/9830d305d91da102f5185e756571bed592f58cd9 (makes them bigger as chat messages)

https://github.com/downforacross/downforacross.com/commit/618e98efda2dd4ed681a4204a951e4af787e9026 (a bad merge that deleted this functionality)

**Comment by stevenhao** [comment]
closed in 7a09c91 and 578fbcf
