### ISSUE TITLE
Add timestamps to chat

### ISSUE THREAD

**Issue by tcdachille** [downforacross/downforacross.com#175]
I'd like to see timestamps added to chat, which would be especially useful when collaborating on a puzzle over an extended period of time

**Comment by stevenhao** [comment]
Good idea! The data should exist already, so it's just a matter of displaying it in the frontend.

**Comment by tcdachille** [comment]
Cool! Can I actually grab this task? I'd love to start contributing but don't have a ton of web dev experience

**Comment by stevenhao** [comment]
That'd be awesome! Are you in the discord? I or another contributor can help you get started if you'd like.

**Comment by tcdachille** [comment]
Sweet! Help getting started would be great. And yep! I joined the discord right when I was opening this issue.

**Comment by kevinl120** [comment]
Is this still being worked on? If not I'd like to take a stab at it!

**Comment by stevenhao** [comment]
Go for it @kevinl120

**Comment by bdenney** [comment]
Can we close this issue? It appears to have been fixed!

**Comment by stevenhao** [comment]
yup thanks again @kevinl120
