### ISSUE TITLE
Shading/circle display error in 3/31/21 puzzle

### ISSUE THREAD

**Issue by frozenpandaman** [downforacross/downforacross.com#183]
NYT display:
![Screen Shot 2021-03-31 at 18 19 09](https://user-images.githubusercontent.com/7245874/113230520-fe35ae00-924d-11eb-87d8-6b295ac59cd3.png)

Down for a Cross display:
![Screen Shot 2021-03-31 at 18 19 28](https://user-images.githubusercontent.com/7245874/113230537-08f04300-924e-11eb-8972-3ea2b8aab253.png)

**Comment by Plasser1** [comment]
This is happening in the the 4/18/21 NYT Puzzle as well
https://downforacross.com/beta/play/13422
Correct circle placements: https://crosswordfiend.com/2021/04/17/sunday-april-18-2021/#ny

**Comment by stevenhao** [comment]
this must be a bug in the puz parser. i wonder if nyt changed something about their encoding.

**Comment by frozenpandaman** [comment]
@stevenhao found another likely .puz parser bug, in 4/21/2020:
![image](https://user-images.githubusercontent.com/7245874/115648300-0e372f80-a2da-11eb-8f0c-fe575e2366a0.png)
![image](https://user-images.githubusercontent.com/7245874/115648320-142d1080-a2da-11eb-9b8b-5d24e39324c6.png)

Should be "R2D2" and "C3PO." Seems to think numbers should be Ts.

**Comment by cameronfreer** [comment]
See also #122

**Comment by JohnHKoh** [comment]
Does anyone have a .puz file they can share the demonstrates the incorrect behavior? That could help in getting to the bottom of this.

**Comment by jackofallspades98** [comment]
github doesn't allow me to attach .puz files in comments, but here's a file that demonstrates the circle issue when uploaded to DfA
https://drive.google.com/file/d/1P_DehmxORtNi2F4rT8NbQCtE3xgIRfaw/view?usp=sharing

**Comment by stevenhao** [comment]
Thanks so much @JohnHKoh  for the fix!

**Comment by stevenhao** [comment]
Turns out the bug was not in the parser, just in the frontend (did not support rectangular grids due to a bug that did a computation based on the number of rows instead of number of columns)
