### ISSUE TITLE
Defaults to "0A" if there's no 1 across

### ISSUE THREAD

**Issue by frozenpandaman** [downforacross/downforacross.com#199]
Not sure if this is technically a bug, but the site by default (on page load) loads a null clue "0A" if there's a nonstandard crossword without a 1 across, e.g. https://downforacross.com/beta/game/1083156-trag

![image](https://user-images.githubusercontent.com/7245874/126454471-50ee2b05-6bcf-4c25-95d8-f05765bd6a87.png)

In this case I'd expect either 1 down or 4 across to be loaded, but the current behavior isn't too bad IMO, just nothing gets loaded by default.

**Comment by JohnHKoh** [comment]
Fixed with #208. 4 across is selected in this case.
