### ISSUE TITLE
Pencil suggestions

### ISSUE THREAD

**Issue by jakob223** [downforacross/downforacross.com#20]
- Clicking the pencil shouldn't take focus away from whichever square you were on
 - There should be a keyboard shortcut for pencil mode

**Comment by stevenhao** [comment]
closed in https://github.com/downforacross/downforacross.com/commit/2e1e8686ea76f01067b140d6faf44f5562686e6b

**Comment by stevenhao** [comment]
the shortcut was implemented already but not documented, it's "." and is now hinted on hover over the icon: https://github.com/downforacross/downforacross.com/commit/bdf97b3a05e35820d973e32a63224ffedc04c9cb
