### ISSUE TITLE
Empty root div created for puzzle with no clues?

### ISSUE THREAD

**Issue by jwarley** [downforacross/downforacross.com#203]
https://downforacross.com/beta/play/15819

"Can you solve this one? Tricky tricky...."

**Comment by frozenpandaman** [comment]
tricky tricky indeed

**Comment by JohnHKoh** [comment]
Fixed with #208, though ideally, we should not even allow such puzzles to be uploaded in the first place, unless unlisted.

**Comment by jwarley** [comment]
![image](https://user-images.githubusercontent.com/12537221/133025386-1981fa7e-2e72-408c-80c3-70ebdc09aa57.png)

Victory at last.
