### ISSUE TITLE
Italics showing up as quotation marks

### ISSUE THREAD

**Issue by frozenpandaman** [downforacross/downforacross.com#243]
Downforacross display:
<img width="203" alt="image" src="https://user-images.githubusercontent.com/7245874/179208800-3edebb2f-b98e-4943-8ae2-61673662c37b.png">

NYT display:
<img width="150" alt="image" src="https://user-images.githubusercontent.com/7245874/179208849-93fafcc4-f87f-4a6c-8851-95df3db3d942.png">

From NYT's 2022/07/13 puzzle.

**Comment by frozenpandaman** [comment]
Happens again in the NYT 2022/10/27 puzzle.

**Comment by zhiyi-zhang-duke** [comment]
I put a pull request for this bug here, just waiting for review:
https://github.com/downforacross/downforacross.com/pull/295

**Comment by zhiyi-zhang-duke** [comment]
@frozenpandaman I believe it's fixed:
![image](https://github.com/downforacross/downforacross.com/assets/68999131/8e693b2b-787a-4d74-a822-1844d6994abf)

**Comment by frozenpandaman** [comment]
Nice, thank you!!
