### ISSUE TITLE
[Feature] show letter attribution at the end

### ISSUE THREAD

**Issue by alectrolytes** [downforacross/downforacross.com#249]
It would be really cool to show who contributed what letter at the end of a multiplayer puzzle.

**Comment by JohnHKoh** [comment]
Try turning on the "Color Attribution" mode.

![image](https://user-images.githubusercontent.com/6465531/208839067-81bd96b5-131f-4e91-98ee-a5db9ec7d966.png)

**Comment by stevenhao** [comment]
i made the color attribution option a paint bucket icon, hopefully it's more noticeable now.

additionally, at the end of the game the check/reveal/reset buttons are hidden (replaced by an icon that opens the replay page) which should further make the color attribution toggle more prominent.

screenshot as of today:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/1988030/211379234-a0ad67db-745e-4d17-be84-4e2122cf6100.png">


closing this issue!
