### ISSUE TITLE
Underlined clues don't render correctly

### ISSUE THREAD

**Issue by zhiyi-zhang-duke** [downforacross/downforacross.com#301]
If you look at one of the recent puzzles:
NY Times, Thursday, January 4, 2024
51 across is rendered as:
<img width="232" alt="image" src="https://github.com/downforacross/downforacross.com/assets/68999131/84b2bf78-ec82-424f-ad5e-6ba1c539d738">
64 across:
<img width="217" alt="image" src="https://github.com/downforacross/downforacross.com/assets/68999131/d92d6fb1-055c-4033-8da3-4517378faba7">
I'm guessing they're just supposed to just be underlined.

**Comment by lllloyd** [comment]
Here's a console command to fix it for today!

```
let els = document.getElementsByClassName("clues--list--scroll--clue--text");
for (const el of els) {
let e = document.createElement("div");
e.innerHTML = el.firstChild.innerText;
el.removeChild(el.firstChild);
el.appendChild(e);
}
```

**Comment by zhiyi-zhang-duke** [comment]
I believe this can be closed!
