### ISSUE TITLE
Unable to load puzzle on local dev server

### ISSUE THREAD

**Issue by flackr** [downforacross/downforacross.com#320]
I'm having an issue which seems very similar to #116, when running the local dev server I see a puzzle list but on trying to load any of them it pauses indefinitely. In dev tools, I noticed there's a request to http://api-staging.foracross.com/api/counters/gid which never succeeds. I'm not sure if the staging server is maybe down?

**Comment by stevenhao** [comment]
thanks, should be fixed now hopefully

**Comment by flackr** [comment]
Thanks, working great! Now I can try to put together some PRs :-)
