### ISSUE TITLE
Visibility into members in room

### ISSUE THREAD

**Issue by hjylewis** [downforacross/downforacross.com#65]
It would be cool to see a list of people currently in the room and the ability to hover over the colored cursors and see who it is

**Comment by stevenhao** [comment]
great idea!

**Comment by stevenhao** [comment]
list of users is added by #83
![image](https://user-images.githubusercontent.com/1988030/77940103-0b037880-726d-11ea-9fa0-9076c147dda6.png)

hover over cursor to see who it is: still TODO, but should be relatively straightforward now

**Comment by carlyrobison** [comment]
I noticed this while crosswording today. Great addition!
