### ISSUE TITLE
Delete gets stuck on blue/correct characters

### ISSUE THREAD

**Issue by sdefranzo** [downforacross/downforacross.com#7]
Would be great if delete was able to skip over correct characters in an incorrect word.

Currently, if you try to backspace through an answer that has a mixture of red and blue characters, it gets stuck on correct characters (you can backspace but nothing happens and it doesn't move on).

It's great that I can't delete blue characters, but if there are additional red characters in the word it'd be nice to be able to hop over the correct square and finish deleting.

E.g.

![34898399-c4ed5c36-f7a7-11e7-8f83-fc5187d67825](https://user-images.githubusercontent.com/10481782/37811514-fca1e97a-2e17-11e8-807b-83b8cc568659.png)

One solution to this is a "clear all incorrect" function, but I sometimes like to leave red squares as a cue to distracted collaborators :)

**Comment by stevenhao** [comment]
closed in #43
