### ISSUE TITLE
Puzzle does not resolve

### ISSUE THREAD

**Issue by sdefranzo** [downforacross/downforacross.com#8]
Two people working on this puzzle
Used check function a few times
All squares are blue, timer is still running and highlight is still blue

Sometimes when multiple participants type an answer the cursor position shifts and skips around, though I've observed this when I'm the only person typing (on a shared game)

https://downforacross.com/game/3880 - this is the only time we've seen this

**Comment by stevenhao** [comment]
fixed in beta!
