### ISSUE TITLE
Can't answer rebuses

### ISSUE THREAD

**Issue by ibrand** [downforacross/downforacross.com#85]
I'm noticing that there doesn't seem to be a way to answer with more than 1 letter in a slot for [Rebus](https://www.nytimes.com/2017/06/01/crosswords/yes-you-can-write-more-than-one-letter-in-a-square.html) answers.

Am I missing something? Or is this an area that needs addressing?

I love this project! 😄

**Comment by stevenhao** [comment]
It's not super easy to discover this, but you can hold shift and type to enter rebuses!
