### ISSUE TITLE
Pause timer when navigating away from page

### ISSUE THREAD

**Issue by sdefranzo** [downforacross/downforacross.com#9]
Ideally when navigating away from the tab, but if you close out of the puzzle window right now, the timer just runs forever and will still be running when returning to the url. Would be nice to be able to take a break and reflect actual time spent on the puzzle.

**Comment by stevenhao** [comment]
Hey thanks for the suggestion!

**Comment by stevenhao** [comment]
implemented this in beta! 9937c6e
