### ISSUE TITLE
Allow searching by disjoint substrings

### ISSUE THREAD

**Issue by TMiguelT** [downforacross/downforacross.com#92]
For example, if I want to find NYT Crosswords from April 2020, my intuition is to type `NY Times April 2020` into the search bar. This doesn't work because downforacross is searching for that entire string in each title, and not finding it because it doesn't exist within a string like `NY Times, Monday, April 27, 2020`. But it's a very common technique to split each token in the search term, and return an result that contains `NY`, `Times`, `April`,  and `2020`. I believe this would be more powerful and intuitive.

**Comment by stevenhao** [comment]
This will be fairly straightforward once we get puzzlelists in redis

**Comment by TMiguelT** [comment]
Have you made this update in redis yet?

**Comment by stevenhao** [comment]
Not yet.
