### ISSUE TITLE
How can users delete a puzzle they uploaded?

### ISSUE THREAD

**Issue by kannandeepti** [downforacross/downforacross.com#93]
I uploaded a puzzle to downforacross.com by mistake (didn't realize it would be hosted publicly forever). Can it be deleted?

**Comment by stevenhao** [comment]
I can make it private or delete it -- let's talk on messenger: https://www.messenger.com/t/steven.hao.14

**Comment by asvin-kumar** [comment]
I'm seeing this after 5 years and I wish I could delete a puzzle of mine? Is there a way to provide a longer term solution to users?
